# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Site settings
#
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

#
# Build settings
#

#
# Conf
#
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      position: "footer"
      index: 1
      permalink: /:basename/

# Include
include: ["_pages"]

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

# Collections
collections:
  sidebars:
    foo: bar

# Permalinks
#permalink: pretty
